export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'AUTH_001',
  ACCOUNT_SUSPENDED = 'AUTH_002',
  ACCOUNT_PENDING = 'AUTH_003',
  ACCOUNT_INACTIVE = 'AUTH_004',
  ACCESS_TOKEN_EXPIRED = 'AUTH_005',
  ACCESS_TOKEN_INVALID = 'AUTH_006',
  REFRESH_TOKEN_EXPIRED = 'AUTH_007',
  REFRESH_TOKEN_INVALID = 'AUTH_008',
  MFA_REQUIRED = 'AUTH_009',
  MFA_INVALID = 'AUTH_010',
  INSUFFICIENT_PERMISSIONS = 'AUTH_011',
  SESSION_REVOKED = 'AUTH_012',

  // Tenant
  TENANT_NOT_FOUND = 'TENANT_001',
  TENANT_SUSPENDED = 'TENANT_002',
  TENANT_DELETED = 'TENANT_003',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_001',
  INVALID_INPUT = 'VALIDATION_002',
  MISSING_REQUIRED_FIELD = 'VALIDATION_003',
  INVALID_DATE_RANGE = 'VALIDATION_004',
  INVALID_FILE_TYPE = 'VALIDATION_005',
  FILE_TOO_LARGE = 'VALIDATION_006',

  // Resource
  RESOURCE_NOT_FOUND = 'RESOURCE_001',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_002',
  RESOURCE_CONFLICT = 'RESOURCE_003',
  RESOURCE_LOCKED = 'RESOURCE_004',
  RESOURCE_DELETED = 'RESOURCE_005',

  // Users
  USER_NOT_FOUND = 'USER_001',
  USER_ALREADY_EXISTS = 'USER_002',
  USER_SUSPENDED = 'USER_003',
  USER_CANNOT_MODIFY_SELF = 'USER_004',
  INCORRECT_PASSWORD = 'USER_005',
  PASSWORD_SAME_AS_OLD = 'USER_006',
  IDENTIFIER_TAKEN = 'USER_007',
  EMAIL_TAKEN = 'USER_008',

  // School Setup
  SESSION_NOT_FOUND = 'SETUP_001',
  SESSION_ALREADY_EXISTS = 'SETUP_002',
  TERM_NOT_FOUND = 'SETUP_003',
  TERM_ALREADY_EXISTS = 'SETUP_004',
  TERM_LIMIT_REACHED = 'SETUP_005',
  CLASS_NOT_FOUND = 'SETUP_006',
  CLASS_ALREADY_EXISTS = 'SETUP_007',
  CLASS_NOT_EMPTY = 'SETUP_008',
  SUBJECT_NOT_FOUND = 'SETUP_009',
  SUBJECT_ALREADY_EXISTS = 'SETUP_010',
  SUBJECT_ALREADY_ASSIGNED = 'SETUP_011',
  SUBJECT_NOT_ASSIGNED = 'SETUP_012',
  DEPARTMENT_NOT_FOUND = 'SETUP_013',
  DEPARTMENT_ALREADY_EXISTS = 'SETUP_014',
  ACTIVE_SESSION_REQUIRED = 'SETUP_015',
  ACTIVE_TERM_REQUIRED = 'SETUP_016',
  CANNOT_DELETE_ACTIVE = 'SETUP_017',
  HAS_LINKED_RESULTS = 'SETUP_018',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_001',
  TOO_MANY_LOGIN_ATTEMPTS = 'RATE_002',

  // Server
  INTERNAL_ERROR = 'SERVER_001',
  SERVICE_UNAVAILABLE = 'SERVER_002',
  DATABASE_ERROR = 'SERVER_003',
  EXTERNAL_SERVICE_ERROR = 'SERVER_004',
}
